# Generated by Django 4.2.3 on 2023-07-10 21:08

from django.db import migrations, models
import stdimage.models
import usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('senha', models.CharField(max_length=64, verbose_name='Senha')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=usuarios.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('facebook', models.CharField(default='#', max_length=128, verbose_name='Facebook')),
                ('twitter', models.CharField(default='#', max_length=128, verbose_name='Twitter')),
                ('instagram', models.CharField(default='#', max_length=128, verbose_name='Instagram')),
                ('linkedin', models.CharField(default='#', max_length=128, verbose_name='Linkedin')),
            ],
            options={
                'verbose_name': 'Usuario',
            },
        ),
    ]
